### ISSUE TITLE
Question: Caching whilst rendering

### ISSUE THREAD

**Issue by badbud65** [Isti115/BlenderRenderController#16]
I haven't been using Blender for very long and I have searched for information regarding my issue. I haven't found anything that answers these questions specifically. *Usually when you write this, the first reply is a link that directly answers your question, if so, great.*

I have set the Disk Cache to a separate NVMe drive that currently has 500 GB capacity and I have found that the rendering is significantly quicker than having the Cache on a normal HDD. Great I thought.

But 500 GB gets consumed rather quickly. What appears to be happening is that old Cache is initially being deleted as new Cache is added , but this stops working (I assume a bug) after approximately 30-40 mins whilst rendering.

I then thought my cache size was to high as I have used two separate tools so that Blender can use all cores on my 3900x. But both tools exhibit the same behaviour with regards to Cache. Therefore I set the Disk Cache file size to 15 GM assuming it was per thread, and that does appear to be the case.

**Tools I've used are:**

1. Yours of course.
2. https://github.com/mikeycal/the-video-editors-render-script-for-blender But I have problem with that "Script Failing Errors #20" 

**My questions are:**

1. Should the Disk cache be deleted continually during the rendering process? If so is this a bug that it isn't being deleted? Or issues with the two scripts above?

2. How much Disk Cache should be being used? As I have it set to 15 GB but even Blender has currently created a cache of 20 GB whilst doing some quick edits on a video. I have estimated that for a 3 hour video that at least 1 TB+ is being used. As I was monitoring what it was deleting and started deleting old cache directories manually when the disk size limit was being reached.

Most likely it's something I haven't understood, here's hoping.

**Comment by isti115** [comment]
Whew, thanks for the well written issue and sorry about the delayed answer, but I'm afraid that I won't be able to provide much help with this. I myself have actually never touched blender's disk cache settings, so I have zero experience with it.
Based on @mikeycal's comment https://github.com/mikeycal/the-video-editors-render-script-for-blender/issues/20#issuecomment-666091930 the VSE Disk Cache feature has only been added recently, which explains why I haven't encountered it while I was using and developing this application. (I have since switched to DaVinci Resolve about one and a half years ago, as it has a very good free version.)

From a programming standpoint the reasonable solution for me would seem to be if the blender team would implement some sort of a shared cache for multiple instances, but I think that it is a very unrealistic thing to ask for, since this is a such a negligible use case.

Finally, to answer your questions:  
1. I don't think that our scripts have to do anything with the deletion of the cache, it should be done by blender. If it's a bug, there might be hope for a fix in the upcoming 2.9 release, which should arrive in August 2020.
2. As usually with these sort of questions I think that there is no simple answer, rather a list of aspects and trade-offs to consider. I guess that it greatly depends on the resolution of the footage, how much space you can afford to allocate for it and finding a sweet point between the gains in speed and losses in capacity.

In the end with these sort of issues it sadly has to come down to the fact that blender was not designed as a video editor and is still not being developed as one, so there will probably always be unusual problems occurring when trying to use it as such. I hope you manage to find an appropriate workflow for what your goals are! :)

**Comment by badbud65** [comment]
This doesn't happen anymore, stopped happening last releases before 2.9, so assumed to be a bug.
